"""
Quick-reference dump: which characters belong to each ascension_stat value
(the counts already in genshin_attribute_counts.txt, but with the actual
character names instead of just a number). Not consumed by any pipeline
step - a human-readable lookup kept alongside genshin_entities.json.
Excludes Traveler's 14 element/gender variants for the same reason
count_attribute_values.py does - see its own comment.
"""
import json
from collections import defaultdict
from pathlib import Path

ENTITIES_PATH = Path(__file__).parent / "output" / "genshin_entities.json"
OUTPUT_PATH = Path(__file__).parent / "output" / "genshin_ascension_stat_characters.txt"


def main():
    all_entities = json.loads(ENTITIES_PATH.read_text(encoding="utf-8"))
    entities = [e for e in all_entities if "traveler" not in e["id"]]

    by_stat = defaultdict(list)
    for e in entities:
        stat = e["attributes"].get("ascension_stat")
        if stat:
            by_stat[stat].append(e["display_name"])

    lines = [f"Genshin characters by ascension_stat ({len(entities)} entities, excludes Traveler)"]
    lines.append("Generated by build_ascension_stat_map.py - re-run after any roster change.")
    lines.append("")

    for stat, names in sorted(by_stat.items(), key=lambda kv: (-len(kv[1]), kv[0])):
        lines.append(f"{stat} ({len(names)})")
        for name in sorted(names):
            lines.append(f"  {name}")
        lines.append("")

    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
