"""
Quick-reference dump: how many GridItems fall into each distinct value of
each attribute (how many Pyro characters, how many HP% ascension-stat
characters, etc.) - not consumed by any pipeline step or by the backend,
just a human-readable sanity check kept alongside genshin_entities.json so
"is this category thin?" has a fast answer without re-deriving it by hand.
Re-run whenever the roster changes. See also GridGeneratorTest's
gridCompositionReport for the equivalent check at the generated-puzzle
level (this is the raw per-attribute count instead).
"""
import json
from collections import Counter
from pathlib import Path

ENTITIES_PATH = Path(__file__).parent / "output" / "genshin_entities.json"
OUTPUT_PATH = Path(__file__).parent / "output" / "genshin_attribute_counts.txt"

DIMENSIONS = [
    "element", "weapon", "region", "rarity", "model", "release_version",
    "local_specialty", "common_material", "boss_material", "ascension_stat",
]


def main():
    entities = json.loads(ENTITIES_PATH.read_text(encoding="utf-8"))

    lines = [f"Genshin GridItem attribute value counts ({len(entities)} entities)"]
    lines.append("Generated by count_attribute_values.py - re-run after any roster change.")
    lines.append("")

    for dimension in DIMENSIONS:
        counts = Counter(
            e["attributes"][dimension] for e in entities if e["attributes"].get(dimension)
        )
        lines.append(f"{dimension} ({len(counts)} distinct values, {sum(counts.values())} entities counted)")
        for value, count in sorted(counts.items(), key=lambda kv: (-kv[1], str(kv[0]))):
            lines.append(f"  {count:>3}  {value}")
        lines.append("")

    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
