# Hand-curated brawler passive-trait data. The Brawl Stars API exposes no
# trait information at all, so this is the sole source of truth - applied in
# normalize.py's map_brawler for every brawler, defaulting to [] for
# brawlers with no listed trait. Keep in sync by hand as Supercell adds
# brawlers/traits.
KNOWN_TRAITS: dict[str, list[str]] = {
    "Bull": ["Damage"],
    "El Primo": ["Damage"],
    "Rosa": ["Damage"],
    "Jacky": ["Damage"],
    "Frank": ["Damage"],
    "Ash": ["Damage"],
    "Trunk": ["Damage"],
    "Hank": ["Damage"],
    "Ollie": ["Damage"],
    "Damian": ["Damage"],
    "Draco": ["Damage"],
    "Darryl": ["Time"],
    "Kit": ["Time"],
    "Edgar": ["Time"],
    "Chuck": ["Time"],
    "Jae-Yong": ["Time"],
    "Sirius": ["Time"],
    "Sam": ["Time"],
    "Eve": ["Hover"],
    "Angelo": ["Hover"],
    "R-T": ["Hover"],
    "Juju": ["Hover"],
    "Shade": ["Hover", "Proximity"],
    "Wendy": ["Hover", "Shield"],
    "Alli": ["Hover", "Enraged"],
    "Buzz": ["Proximity"],
    "Cordelius": ["Proximity"],
    "Lily": ["Proximity"],
    "Buster": ["Proximity"],
    "Chester": ["Random"],
    "Pearl": ["Increased Damage"],
    "Clancy": ["Power Token"],
    "Doug": ["Super Healing"],
    "Berry": ["Super Healing"],
    "Glowy": ["Super Healing"],
    "Gigi": ["Dodge"],
    "Kenji": ["Lifesteal"],
    "Max": ["Movement"],
    "Bolt": ["Movement", "Speed"],
}
